pluginPrefix: "<#FC7B00><bold>DataMigration</bold> <white><bold>»</bold> "
discordWebhookUrl: ""


lang:
  missing-permission: "<red>Missing permission"
  migration-fail: "<red>Migration Failed! Contact an admin!"
  migration-success: "<green>Migration successful!"