name: DataMigrator
version: ${version}
author: budi1200
main: si.budimir.dataMigrator.DataMigrator
api-version: 1.17
depends: [LuckPerms, Autorank]
commands:
  migration:
    description: Main DM command
    usage: /migration

permissions:
  datamigrator.admin:
    description: Reload the plugin
    default: op